//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: dynamic-location-group.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
@_implementationOnly import GRPC
@_implementationOnly import NIO
import SwiftProtobuf


/// Usage: instantiate `DistributedMatchEngine_DynamicLocGroupApiClient`, then call methods of this protocol to make API calls.
internal protocol DistributedMatchEngine_DynamicLocGroupApiClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: DistributedMatchEngine_DynamicLocGroupApiClientInterceptorFactoryProtocol? { get }

  func sendToGroup(
    _ request: DistributedMatchEngine_DlgMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<DistributedMatchEngine_DlgMessage, DistributedMatchEngine_DlgReply>
}

extension DistributedMatchEngine_DynamicLocGroupApiClientProtocol {
  internal var serviceName: String {
    return "distributed_match_engine.DynamicLocGroupApi"
  }

  /// Unary call to SendToGroup
  ///
  /// - Parameters:
  ///   - request: Request to send to SendToGroup.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sendToGroup(
    _ request: DistributedMatchEngine_DlgMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<DistributedMatchEngine_DlgMessage, DistributedMatchEngine_DlgReply> {
    return self.makeUnaryCall(
      path: "/distributed_match_engine.DynamicLocGroupApi/SendToGroup",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendToGroupInterceptors() ?? []
    )
  }
}

internal protocol DistributedMatchEngine_DynamicLocGroupApiClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'sendToGroup'.
  func makeSendToGroupInterceptors() -> [ClientInterceptor<DistributedMatchEngine_DlgMessage, DistributedMatchEngine_DlgReply>]
}

internal final class DistributedMatchEngine_DynamicLocGroupApiClient: DistributedMatchEngine_DynamicLocGroupApiClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: DistributedMatchEngine_DynamicLocGroupApiClientInterceptorFactoryProtocol?

  /// Creates a client for the distributed_match_engine.DynamicLocGroupApi service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: DistributedMatchEngine_DynamicLocGroupApiClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol DistributedMatchEngine_DynamicLocGroupApiProvider: CallHandlerProvider {
  var interceptors: DistributedMatchEngine_DynamicLocGroupApiServerInterceptorFactoryProtocol? { get }

  func sendToGroup(request: DistributedMatchEngine_DlgMessage, context: StatusOnlyCallContext) -> EventLoopFuture<DistributedMatchEngine_DlgReply>
}

extension DistributedMatchEngine_DynamicLocGroupApiProvider {
  internal var serviceName: Substring { return "distributed_match_engine.DynamicLocGroupApi" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SendToGroup":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<DistributedMatchEngine_DlgMessage>(),
        responseSerializer: ProtobufSerializer<DistributedMatchEngine_DlgReply>(),
        interceptors: self.interceptors?.makeSendToGroupInterceptors() ?? [],
        userFunction: self.sendToGroup(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol DistributedMatchEngine_DynamicLocGroupApiServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'sendToGroup'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSendToGroupInterceptors() -> [ServerInterceptor<DistributedMatchEngine_DlgMessage, DistributedMatchEngine_DlgReply>]
}
