use_frameworks!

platform :ios, '12.0'

# Default Specs.git:
source 'https://github.com/CocoaPods/Specs.git'
# MobiledgeX Private Trunk for Specs.git equivalent, , if not using "../../IOSMatchingEngineSDK/":
source 'https://github.com/mobiledgex/PrivatePodTrunk.git'

target 'SkeletonApp' do
  pod 'MobiledgeXiOSLibrary', :path => '../../IOSMatchingEngineSDK/'

  pod 'PromisesSwift'

  pod 'DropDown'
  pod 'SwiftLocation'
  pod 'SwiftyJSON'
  
  pod 'GoogleMaps', '= 3.3.0'
  pod 'GoogleSignIn'

  pod 'SwiftLog'
  
  pod 'SPPermission', '= 2.9'
end
